apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      description: Git URL репозитория
    - name: branch
      default: main
      description: Ветка для checkout
  tasks:
    - name: clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: "true"
        - name: submodules
          value: "false"

    - name: lint
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskSpec:
        workspaces:
          - name: source
        steps:
          - name: run-flake8
            image: python:3.9-slim
            workingDir: /workspace/source
            script: |
              #!/usr/bin/env sh
              pip install --no-cache-dir flake8
              python -m flake8 --count --max-complexity=10 --max-line-length=127 --statistics
      runAfter:
        - clone

    - name: tests
      runAfter:
        - clone
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: args
          value: "-v --with-spec --spec-color"
        - name: database_uri
          value: "sqlite:///test.db"
