apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
    - name: build-image
      type: string
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: lint
      taskRef:
        name: lint
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: tests
      taskRef:
        name: tests
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: build
      taskRef:
        name: build
      runAfter:
        - tests
      params:
        - name: build-image
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - build
      params:
        - name: build-image
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: pipeline-workspace
